package de.spektrumprojekt.i.ranker;

public enum RankerConfigurationFlag {

    ONLY_USE_TERM_MATCHER_FEATURE,

    ONLY_USE_TERM_MATCHER_FEATURE_BUT_LEARN_FROM_FEATURES,

    DISCUSSION_PARTICIPATION_LEARN_FROM_PARENT_MESSAGE,

    DISCUSSION_PARTICIPATION_LEARN_FROM_ALL_PARENT_MESSAGES,

    DO_NOT_USE_DISCUSSION_FEATURES,

    DO_NOT_USE_CONTENT_MATCHER_FEATURE,

    USE_DIRECTED_USER_MODEL_ADAPTATION,

    USE_MESSAGE_GROUP_SPECIFIC_USER_MODEL,

    LEARN_NEGATIVE,

    USE_HALF_SCORE_ON_NON_PARTICIPATING_ANSWERS,

    // USE_INVERSE_TERM_FREQUENCY,

    USE_CONTENT_MATCH_FEATURE_OF_SIMILAR_USERS,

    // will not infer observations from ratings
    NO_LEARNING_ONLY_RANKING,

    // only usefull for analyzing term uniqness
    NO_USER_SPECIFIC_COMMANDS;

}