package de.spektrumprojekt.i.ranker;

public enum RankerConfigurationFlag {
    ONLY_USE_TERM_MATCHER_FEATURE,
    DO_NOT_USE_DISCUSSION_FEATURES,
    DO_NOT_USE_TERM_MATCHER_FEATURE,
    USE_DIRECTED_USER_MODEL_ADAPTATION,
    USER_MESSAGE_GROUP_SPECIFIC_USER_MODEL;
}